// scripts/probe-hooks.mjs — spike harness: spawn one claude via node-pty
// with Notification / PreToolUse / Stop hooks wired to a temp capture sink.
// The capture sink appends raw stdin JSON to a file; this script prints the
// capture file path on exit.
//
// Usage:
//   node scripts/probe-hooks.mjs
//   CLAUDE_BIN=/path/to/claude node scripts/probe-hooks.mjs
//
// Capture file: /tmp/probe-hooks-capture-<uuid>.jsonl

import { spawn as ptySpawn } from 'node-pty';
import { writeFileSync, mkdirSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

// CLAUDE_BIN is user-controlled — treat as untrusted; never interpolate into
// a shell string. Pass as argv[0] only.
const CLAUDE_BIN = process.env.CLAUDE_BIN || 'claude';
const cwd = process.cwd();

const runId = randomUUID();
const captureFile = join(tmpdir(), `probe-hooks-capture-${runId}.jsonl`);

// Write capture file initially empty so the path is valid immediately.
writeFileSync(captureFile, '');

// Write a self-contained emitter script to a temp file.
// It reads all of stdin, appends it as one line to the capture file, exits 0.
// This runs for EVERY hook invocation (Notification, PreToolUse, Stop).
const emitterFile = join(tmpdir(), `probe-hooks-emitter-${runId}.mjs`);
const emitterSrc = [
  '#!/usr/bin/env node',
  '// Auto-generated by probe-hooks.mjs — do not edit.',
  "import { appendFileSync } from 'node:fs';",
  `const captureFile = ${JSON.stringify(captureFile)};`,
  'const chunks = [];',
  "process.stdin.on('data', c => chunks.push(c));",
  "process.stdin.on('end', () => {",
  '  const raw = Buffer.concat(chunks).toString();',
  '  appendFileSync(captureFile, raw.trim() + "\\n");',
  '  process.exit(0);',
  '});',
].join('\n');
writeFileSync(emitterFile, emitterSrc, { mode: 0o755 });

// Build the settings JSON that wires all three hook events to the emitter.
// Each event key maps to an array of matcher objects; matcher object has a
// "hooks" array of {type, command} objects.
const emitterCmd = `node ${emitterFile}`;
const hookEntry = [{ hooks: [{ type: 'command', command: emitterCmd }] }];
const settingsObj = {
  hooks: {
    Notification: hookEntry,
    PreToolUse: hookEntry,
    Stop: hookEntry,
  },
};
const settingsFile = join(tmpdir(), `probe-hooks-settings-${runId}.json`);
writeFileSync(settingsFile, JSON.stringify(settingsObj));

// argv-form spawn — no shell string interpolation of CLAUDE_BIN or cwd.
const args = [
  '--settings', settingsFile,
  '--print',
  'say only the word pong, nothing else',
];

console.log(`[probe-hooks] capture file: ${captureFile}`);
console.log(`[probe-hooks] settings:     ${settingsFile}`);
console.log(`[probe-hooks] emitter:      ${emitterFile}`);
console.log(`[probe-hooks] spawning:     ${CLAUDE_BIN} ${args.join(' ')}`);

const pty = ptySpawn(CLAUDE_BIN, args, {
  name: 'xterm-256color',
  cols: 120,
  rows: 30,
  cwd,
  env: { ...process.env, TERM: 'xterm-256color' },
});

let outputBuf = '';
pty.onData(chunk => { outputBuf += chunk; });

pty.onExit(({ exitCode, signal }) => {
  console.log(`[probe-hooks] claude exited  code=${exitCode} signal=${signal}`);
  console.log(`[probe-hooks] stdout preview: ${outputBuf.replace(/\x1b\[[\d;]*[A-Za-z]/g, '').slice(0, 200)}`);
  // Print capture path last so callers can grab it from the final line.
  console.log(`[probe-hooks] capture: ${captureFile}`);
  process.exit(exitCode ?? 0);
});
